//
// Generated file, do not edit! Created by nedtool 5.6 from beaconing/obsolete/SwarmBeacon.msg.
//

#ifndef __SWARMBEACON_M_H
#define __SWARMBEACON_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include <inet/common/geometry/common/Coord.h>
#include <inet/common/packet/chunk/FieldsChunk.h>
#include <inet/linklayer/common/MacAddress.h>
typedef inet::Coord Coord;
typedef inet::FieldsChunk FieldsChunk;
typedef inet::MacAddress MacAddress;
// }}

/**
 * Class generated from <tt>beaconing/obsolete/SwarmBeacon.msg:35</tt> by nedtool.
 * <pre>
 * class SwarmBeacon extends FieldsChunk
 * {
 *     uint16_t magicNo;       // a magic number identifying beacons
 *     uint16_t version;       // version of the SwarmStack protocol
 *     uint32_t seqno;         // sequence number
 *     MacAddress senderId;      // Mac address of sender, used as sender id
 * 
 *     Coord currPosition;  // current position in given coordinate system
 *     Coord currVelocity;  // current direction vector
 * }
 * </pre>
 */
class SwarmBeacon : public ::FieldsChunk
{
  protected:
    uint16_t magicNo;
    uint16_t version;
    uint32_t seqno;
    MacAddress senderId;
    Coord currPosition;
    Coord currVelocity;

  private:
    void copy(const SwarmBeacon& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SwarmBeacon&);

  public:
    SwarmBeacon();
    SwarmBeacon(const SwarmBeacon& other);
    virtual ~SwarmBeacon();
    SwarmBeacon& operator=(const SwarmBeacon& other);
    virtual SwarmBeacon *dup() const override {return new SwarmBeacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint16_t getMagicNo() const;
    virtual void setMagicNo(uint16_t magicNo);
    virtual uint16_t getVersion() const;
    virtual void setVersion(uint16_t version);
    virtual uint32_t getSeqno() const;
    virtual void setSeqno(uint32_t seqno);
    virtual MacAddress& getSenderId();
    virtual const MacAddress& getSenderId() const {return const_cast<SwarmBeacon*>(this)->getSenderId();}
    virtual void setSenderId(const MacAddress& senderId);
    virtual Coord& getCurrPosition();
    virtual const Coord& getCurrPosition() const {return const_cast<SwarmBeacon*>(this)->getCurrPosition();}
    virtual void setCurrPosition(const Coord& currPosition);
    virtual Coord& getCurrVelocity();
    virtual const Coord& getCurrVelocity() const {return const_cast<SwarmBeacon*>(this)->getCurrVelocity();}
    virtual void setCurrVelocity(const Coord& currVelocity);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SwarmBeacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SwarmBeacon& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SWARMBEACON_M_H

