//
// Generated file, do not edit! Created by nedtool 5.6 from beaconing/base/Beacon.msg.
//

#ifndef __BEACON_M_H
#define __BEACON_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include <inet/common/geometry/common/Coord.h>
#include <inet/common/packet/chunk/FieldsChunk.h>
#include <inet/linklayer/common/MacAddress.h>
#include "../renewalbeaconing/Nbt.h"

typedef inet::Coord Coord;
typedef inet::FieldsChunk FieldsChunk;
typedef inet::MacAddress MacAddress;
typedef std::list<Nbt> Nnbt;
// }}

/**
 * Class generated from <tt>beaconing/base/Beacon.msg:35</tt> by nedtool.
 * <pre>
 * class Beacon extends FieldsChunk
 * {
 *     uint16_t magicNo;       // a magic number identifying beacons
 *     uint16_t version;       // version of the SwarmStack protocol
 *     uint32_t seqno;         // sequence number
 *     MacAddress senderId;      // Mac address of sender, used as sender id
 * 
 *     Nnbt nnbt;
 * 
 *     int currI;
 *     int currJ;
 *     string currentRoadId;
 *     Coord currPosition;  // current position in given coordinate system
 *     Coord currVelocity;  // current direction vector
 *     double currT;
 * }
 * </pre>
 */
class Beacon : public ::FieldsChunk
{
  protected:
    uint16_t magicNo;
    uint16_t version;
    uint32_t seqno;
    MacAddress senderId;
    Nnbt nnbt;
    int currI;
    int currJ;
    ::omnetpp::opp_string currentRoadId;
    Coord currPosition;
    Coord currVelocity;
    double currT;

  private:
    void copy(const Beacon& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Beacon&);

  public:
    Beacon();
    Beacon(const Beacon& other);
    virtual ~Beacon();
    Beacon& operator=(const Beacon& other);
    virtual Beacon *dup() const override {return new Beacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint16_t getMagicNo() const;
    virtual void setMagicNo(uint16_t magicNo);
    virtual uint16_t getVersion() const;
    virtual void setVersion(uint16_t version);
    virtual uint32_t getSeqno() const;
    virtual void setSeqno(uint32_t seqno);
    virtual MacAddress& getSenderId();
    virtual const MacAddress& getSenderId() const {return const_cast<Beacon*>(this)->getSenderId();}
    virtual void setSenderId(const MacAddress& senderId);
    virtual Nnbt& getNnbt();
    virtual const Nnbt& getNnbt() const {return const_cast<Beacon*>(this)->getNnbt();}
    virtual void setNnbt(const Nnbt& nnbt);
    virtual int getCurrI() const;
    virtual void setCurrI(int currI);
    virtual int getCurrJ() const;
    virtual void setCurrJ(int currJ);
    virtual const char * getCurrentRoadId() const;
    virtual void setCurrentRoadId(const char * currentRoadId);
    virtual Coord& getCurrPosition();
    virtual const Coord& getCurrPosition() const {return const_cast<Beacon*>(this)->getCurrPosition();}
    virtual void setCurrPosition(const Coord& currPosition);
    virtual Coord& getCurrVelocity();
    virtual const Coord& getCurrVelocity() const {return const_cast<Beacon*>(this)->getCurrVelocity();}
    virtual void setCurrVelocity(const Coord& currVelocity);
    virtual double getCurrT() const;
    virtual void setCurrT(double currT);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Beacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Beacon& obj) {obj.parsimUnpack(b);}


#endif // ifndef __BEACON_M_H

