//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
//

cplusplus {{
#include <inet/common/geometry/common/Coord.h>
#include <inet/common/packet/chunk/FieldsChunk.h>
#include <inet/linklayer/common/MacAddress.h>
#include "../renewalbeaconing/Nbt.h"

typedef inet::Coord Coord;
typedef inet::FieldsChunk FieldsChunk;
typedef inet::MacAddress MacAddress;
typedef std::list<Nbt> Nnbt;

}}

class noncobject Coord;
class noncobject FieldsChunk;
class noncobject MacAddress;
class noncobject Nnbt;

class Beacon extends FieldsChunk
{
    uint16_t    magicNo;       // a magic number identifying beacons
    uint16_t    version;       // version of the SwarmStack protocol
    uint32_t    seqno;         // sequence number
    MacAddress  senderId;      // Mac address of sender, used as sender id
	
	Nnbt nnbt;
	
	int			 currI;
	int			 currJ;
	string 	     currentRoadId;
    Coord        currPosition;  // current position in given coordinate system
    Coord        currVelocity;  // current direction vector
    double		 currT;
}
